DUT = DataController
VERILOG_SOURCES += $(PWD)/../../rtl/Packetizer.v $(PWD)/../../rtl/SimpleMac.v $(PWD)/../../rtl/lfsr.v $(PWD)/../../rtl/CRC32.v $(PWD)/../../rtl/SimpleMacFifo.v

include ../common.mk
